### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [bakkerthehacker/bramqp#47]
Hi.

If the **arguments** is not empty (see JSON config below), the **exchange.declare** would return the _"Cannot read property 'call' of undefined"_. If the **arguments** contains nothing then **exchange.declare** succeeds.

Please, advise.

```javascript
{
  "name":         "x-ae",
  "description":  "Alternative Exchange",
  "type":         "direct",
  "passive":      false,
  "durable":      true,
  "auto_delete":  false,
  "internal":     false,
  "no_wait":      false,
  "arguments":    {
    "x-dead-letter-exchange":   "x-dl"
  }
}
```

This is the trace:
```
at FrameSerializer.serializeValue (backend/node_modules/bramqp/lib/frameSerializer.js:284:35)
      at FrameSerializer.serializeTable (backend/node_modules/bramqp/lib/frameSerializer.js:273:9)
      at FrameSerializer.serializeFields (backend/node_modules/bramqp/lib/frameSerializer.js:304:34)
      at FrameSerializer.serializeFrameMethod (backend/node_modules/bramqp/lib/frameSerializer.js:336:7)
      at ConnectionHandle.methodBuffer (backend/node_modules/bramqp/lib/connectionHandle.js:378:23)
      at ConnectionHandle.method (backend/node_modules/bramqp/lib/connectionHandle.js:347:25)
      at Object.declare (backend/node_modules/bramqp/lib/connectionHandle.js:121:12)
      at RMQInfra._mapper (rmqinfra.js:65:40)
      at Array.map (native)
      at RMQInfra._recreate_exchanges (rmqinfra.js:92:41)
      at RMQInfra.recreate (rmqinfra.js:111:14)
      at Object.on_initialized (rmqinfra_spec.js:32:27)
      at RMQConnector.<anonymous> (rmqconnector.js:32:41)
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:697:13
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:52:16
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:272:32
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:44:16
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:694:17
      at backend/node_modules/bramqp/node_modules/async/lib/async.js:173:37
      at ConnectionHandle.<anonymous> (backend/node_modules/bramqp/lib/connectionHandle.js:315:6)
      at FrameParser.<anonymous> (backend/node_modules/bramqp/lib/connectionHandle.js:141:8)
      at FrameParser.parseFrameMethod (backend/node_modules/bramqp/lib/frameParser.js:273:7)
      at FrameParser.parseFrameEnd (backend/node_modules/bramqp/lib/frameParser.js:415:63)
      at FrameParser.parseFramePayload (backend/node_modules/bramqp/lib/frameParser.js:392:16)
      at FrameParser.parseFrameStart (backend/node_modules/bramqp/lib/frameParser.js:374:16)
      at FrameParser.parse (backend/node_modules/bramqp/lib/frameParser.js:433:57)
      at Socket.<anonymous> (backend/node_modules/bramqp/lib/connectionHandle.js:40:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

**Comment by bakkerthehacker** [comment]
The data passed into arguments must have a type specified along with it to ensure that things like strings and integers get serialized into the correct AMQP type.  


This is documented in the [Value Types](https://github.com/bakkerthehacker/bramqp/blob/master/doc/Value%20Types.md) page.  

In this case, The `arguments` should look like:

```javascript
  "arguments":    {
    "x-dead-letter-exchange":   {
      type: "Long string",
      data: "x-dl"
    }
  }
```

It would be nice if the parser/serializer gave more meaningful error messages.  This improvement is tracked in issue #13.
