### ISSUE TITLE
Problem with server messages

### ISSUE THREAD

**Issue by NumminorihSF** [bakkerthehacker/bramqp#51]
There is a problem with rabbitmq:
Then server start block new messages, client emits TypeError.
To reproduce this:

shell: `rabbitmqctl set_vm_memory_high_watermark 0`

node.js code:
```js
var bramqp = require('bramqp');
var net = require('net');

var socket = net.connect({
  port : 5672
});

bramqp.initialize(socket, 'rabbitmq/full/amqp0-9-1.stripped.extended', function(error, handle) {
  handle.openAMQPCommunication('guest', 'guest', true, function(seriesCallback) {
    handle.basic.publish(1, '', 'hello', false, false, function() {
      handle.content(1, 'basic', {}, 'Hello World!', function(){});
    });
  });
});
```

stack trace:
```
eventsevents.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'field' of undefined
    at FrameParser.parseFrameMethod (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/frameParser.js:268:49)
    at FrameParser.parseFrameEnd (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/frameParser.js:413:63)
    at FrameParser.parseFramePayload (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/frameParser.js:390:16)
    at FrameParser.parseFrameStart (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/frameParser.js:372:16)
    at FrameParser.parse (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/frameParser.js:431:57)
    at Socket.<anonymous> (/home/numminorihsf/Projects/iojs/rabbit/node_modules/bramqp/lib/connectionHandle.js:45:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10).js:154
```
The reason is that in spec there are no methods ("blocked", "undlocked") with ids (60, 61). So there is an error with it.
Please, update spec for rabbitmq.
https://www.rabbitmq.com/resources/specs/amqp0-9-1.extended.xml

**Comment by NumminorihSF** [comment]
And I did not check another specs. May be they old either.

**Comment by bakkerthehacker** [comment]
Wow this is rather unexpected.  I would not think that these specifications could be updated in this way.  Thanks for finding this.  I cannot use the full versions of the spec, as it is not compatible with the MIT license but the stripped version does include these new methods.  I will update with the new specs shortly.

**Comment by bakkerthehacker** [comment]
This has been updated in b4108789 and will be released along with your other proposed changes.
