### ISSUE TITLE
Passing null queue to handle.queue.declare() fails assertions

### ISSUE THREAD

**Issue by ben-page** [bakkerthehacker/bramqp#57]
### Problem
Calling `queue.declare()` with `null` as the value of the `queue` parameter causes `bramqp` to fail the assertion tests. The specification says ["The queue name MAY be empty"](https://www.rabbitmq.com/amqp-0-9-1-reference.html). And (apparently) this used to work in `bramqp` as the the RPC example ([rpc_client.js](https://github.com/bakkerthehacker/bramqp/blob/master/tutorial/6%20RPC/rpc_client.js)) has this line:

```
self.handle.queue.declare(1, null, false, false, true, false, false, {});
```
Which throws the following error:
```
TypeError: Cannot read property 'length' of null
    at Object.length (C:\XXX\node_modules\bramqp\lib\assertion.js:6:16)
    at module.exports.checkAssertion (C:\XXX\node_modules\bramqp\lib\assertion.js:31:39)
    at FrameSerializer.serializeFields (C:\XXX\node_modules\bramqp\lib\frameSerializer.js:275:4)
    at FrameSerializer.serializeFrameMethod (C:\XXX\node_modules\bramqp\lib\frameSerializer.js:305:7)
    at ConnectionHandle.methodBuffer (C:\XXX\node_modules\bramqp\lib\connectionHandle.js:333:23)
    at ConnectionHandle.method (C:\XXX\node_modules\bramqp\lib\connectionHandle.js:299:25)
    at Object.declare (C:\XXX\node_modules\bramqp\lib\connectionHandle.js:91:12)
```

### Solution
Replacing `null` with an empty string passes the assertion.

```
self.handle.queue.declare(1, '', false, false, true, false, false, {});
```

### Conclusion
I think the assertion should accept `null` or `undefined` as a valid empty value. Or, at least, the examples should be updated.

**Comment by bakkerthehacker** [comment]
Hi thanks for the bug report.  This looks to be an issue with the example that does violate the spec, even though RabbitMQ silently ignores it.

This has been fixed in the docs in the 3 Publish Subscribe and 6 RPC tutorials.
